// LOGIN PROCESS
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGGED_FAILED = 'LOGGED_FAILED';
export const LOGGED_SUCCESSFULLY = 'LOGGED_SUCCESSFULLY';
export const LOGGED_CLEAR = 'LOGGED_CLEAR';

// EMPLOYEE LISTING PROCESS
export const GET_EMPLOYEES_REQUEST = "GET_EMPLOYEES_REQUEST";
export const GET_EMPLOYEES_FAILED = 'GET_EMPLOYEES_FAILED';
export const GET_EMPLOYEES_SUCCESSFULLY = 'GET_EMPLOYEES_SUCCESSFULLY';
export const GET_EMPLOYEES_CLEAR = 'GET_EMPLOYEES_CLEAR';
export const EMPLOYEE_SEARCH = 'EMPLOYEE_SEARCH';

// EMPLOYEE DETAIL PROCESS
export const GET_EMPLOYEE_DETAIL_REQUEST = 'GET_EMPLOYEE_DETAIL_REQUEST';
export const GET_EMPLOYEE_DETAIL_FAILED = 'GET_EMPLOYEES_DETAIL_FAILED';
export const GET_EMPLOYEE_DETAIL_SUCCESSFULLY = 'GET_EMPLOYEES_DETAIL_SUCCESSFULLY';
export const GET_EMPLOYEE_DETAIL_CLEAR = 'GET_EMPLOYEE_DETAIL_CLEAR';

// ADD UPDATE EMPLOYEE DETAIL PROCESS
export const ADD_UPDATE_EMPLOYEE_DETAIL_FAILED = 'ADD_UPDATE_EMPLOYEE_DETAIL_FAILED';
export const ADD_UPDATE_EMPLOYEE_DETAIL_SUCCESSFULLY = 'ADD_UPDATE_EMPLOYEE_DETAIL_SUCCESSFULLY';
export const ADD_UPDATE_EMPLOYEE_DETAIL_CLEAR = 'ADD_UPDATE_EMPLOYEE_DETAIL_CLEAR';
export const ADD_UPDATE_EMPLOYEE_DETAIL_BEGIN = 'ADD_UPDATE_EMPLOYEE_DETAIL_BEGIN';

